/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleproject6;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) {
        int [][] matrix = new int [4][4];
        boolean x = false;
        int opcion;
        Scanner sn = new Scanner(System.in);
        boolean on = false;
        boolean enrangof;
        boolean enrangoc;
        while (!x){
            System.out.println("----------------------------");
            System.out.println("1. Rellenar la matriz");
            System.out.println("2. Suma de fila");
            System.out.println("3. Suma de columna");
            System.out.println("4. Suma de diagonal");
            System.out.println("5. Suma de diagonal inversa");
            System.out.println("6. Media de la matriz");
            System.out.println("7. Mostrar matrix");
            System.out.println("8. Salir");
            try{
                System.out.println("Escribe una opcion");
                opcion = sn.nextInt();
                switch (opcion) {
                    case 1:
                        System.out.println("Matriz rellenada");
                        matrix =  FillMatrix(matrix);
                        on = true;
                        break;
                    case 2:
                        if(on != true){
                            System.out.println("Debes rellenar la matriz");
                        }
                        else{
                            enrangof = false;
                            int op = 0;
                            while(!enrangof){
                                for(int e = 1;e<matrix.length+1;e++){
                                    System.out.println("Fila: "+e);
                                }
                                op = sn.nextInt();
                                if(op<1 || op>matrix.length){
                                    System.out.println("Escribe una opcion");
                                }
                                else{
                                    enrangof = true;
                                }
                            }
                            int w = SumarFilas(matrix, op);
                            System.out.println(w);
                        }
                        break;
                    case 3:
                        if(on != true){
                            System.out.println("Debes rellenar la matriz");
                        
                        }
                        else{
                            enrangoc = false;
                            int op2 = 0;
                            while(!enrangoc){
                                for(int e = 1;e<matrix.length+1;e++){
                                    System.out.println("Columna: "+e);
                                }
                                op2 = sn.nextInt();
                                if(op2<1 || op2>matrix.length){
                                    System.out.println("Escribe una opcion");
                                }
                                else{
                                    enrangoc = true;
                                }
                            }
                            int p = SumarColumna(matrix, op2);
                            System.out.println(p);
                        }
                        break;
                    case 4:
                        if(on != true){
                            System.out.println("Debes rellenar la matriz");
                        }
                        else{
                            int q = SumarDiagonal(matrix);
                            System.out.println(q);
                        }
                        break;
                    case 5:
                        if(on != true){
                            System.out.println("Debes rellenar la matriz");
                        }
                        else{
                            int r = SumarDiagonalInversa(matrix);
                            System.out.println(r);
                        }
                        break;
                    case 6:
                        if(on != true){
                            System.out.println("Debes rellenar la matriz");
                        }
                        else{
                            int num = Media(matrix);
                            System.out.println(num);
                        }
                        break;
                    case 7:
                        String[] num = MostrarMatrix(matrix);
                        for(String matriz: num){
                            System.out.println(matriz);
                        }
                        break;

                    case 8:
                        x=true;
                        break;
                    default:
                        System.out.println("Escribe una opcion");
                }
            } catch (java.util.InputMismatchException e) {
                 System.out.println("Escribe solo numeros");
                 sn.next();
            }
                
        }
    }
    public static int[][] FillMatrix(int[][] matrix){
        int z = 1;
        for(int x=0;x<matrix.length;x++){    
            for(int y=0;y<matrix.length;y++){
                matrix[x][y] = z;
                z++;
            }
        }
    return matrix;
    }
    public static int SumarFilas(int[][] matrix, int fila){
        int x = 0;
        for(int y: matrix[fila-1]){
            x = x + y;
        }
        return x;
    }
    public static int SumarColumna(int[][] matrix, int columna){
        int x = 0;
        for (int[] z : matrix) {
            int y = z[columna-1];
            x = x + y;
        }
        return x;
    }
    public static int SumarDiagonal(int[][]matrix){
        int x = 0;
        for(int z = 0;z<matrix.length; z++){
            int y = matrix[z][z];
            x = x + y;
        }
        return x;
    }
    public static int SumarDiagonalInversa(int[][] matrix){
        int x = 0;
        int z = 0;
        for(int w = matrix.length-1;z<matrix.length; z++,w--){
            int y = matrix[z][w];
            x = x + y;
        }
        return x;
    }
    public static String[] MostrarMatrix(int[][] matrix){
        String [][] num = new String [4][4];
        int z=0;
        for(int x = 0;x<matrix.length; x++){
            for(int y = 0;y<matrix.length; y++){
                num[x][y] = String.valueOf(matrix[x][y]);
                z++;
            }
        }
        String[] fila = new String[4];
        int b = 0;
        for(String[] a: num){
            fila[b] = String.join(" ", a);
            b++;
        }
        return fila;
        }
    public static int Media(int[][] matrix){
        int z = 0;
        for(int x=0;x<matrix.length;x++){    
            for(int y=0;y<matrix.length;y++){
                z = z + matrix[x][y];
            }
        }
        z = z/(matrix.length*matrix[0].length);
        return z;
    }
}
