/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Assignment8;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        String input = "Seg?n un estudio de una universidad inglesa, no importa el orden en el que las letras est?n escritas, la ?nica cosa importante es que la primera y ?ltima letra est?n escritas en la posici?n correcta. El resto pueden estar totalmente mal y a?n podr?s leerlo sin problemas. Esto es porque no leemos cada letra por s? misma. sino la palabra como un todo. Personalmente me parece incre?ble.";
        Assignment8 d = new Assignment8(input);
        System.out.println(d);
    }
}
